spring:
  application:
    name: wms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms
    username: root
    password: 123456
  mvc:
    servlet:
      path: /wms/api


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ikun.wms.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true


file:
  upload-path: classpath:static/img/upload
  access-path: /img/upload/